# format = """\
# $all\
# $directory$character"""

[zig]
symbol = "\\[zig\\] "

[python]
symbol = "\\[py\\] "

[golang]
symbol = "\\[go\\] "

[ruby]
disabled = true

[lua]
disabled = true

[rust]
disabled = true

[package]
disabled = true

